### ISSUE TITLE
Controllers not extending yieldTemplates

### ISSUE THREAD

**Issue by FredericoC** [iron-meteor/iron-router#249]
I have the following (Coffescript):

```
Router.configure
  layoutTemplate: 'layout'
  notFoundTemplate: 'notFound'
  loadingTemplate: 'layoutLoading'

  yieldTemplates:
    layoutMasthead: {to: 'mastHeader'}
    uploadQueue: {to: 'uploadQueue'}
    layoutFooter: {to: 'footer'}
```

```
@GPRouteController = RouteController.extend
  customLoading: ->
    if @ready()
      NProgress.done()
    else
      NProgress.start()
      @stop()
```

```
ProjectController = GPRouteController.extend
  yieldTemplates:
    projectHeaderNav: {to: 'header'}

  projectExists: ->
    unless gp.Permission.canViewProject(Meteor.userId(), @params.projectId)
      @redirect('projects.forbidden')
      @stop()

  before: [
    ->
      @subscribe("project", @params.projectId).wait()
      @subscribe("project.externalShared.user.list", @params.projectId).wait()
    ->
      @customLoading()
    ->
      @projectExists()
    ->
      Session.set('projectId', @params.projectId)
  ]
```

```
  @route 'projects.plans',
    path: '/projects/:projectId/plans'
    template: 'plans'
    controller: ProjectPlansController
```

The "before" hooks extend perfectly, but the "yieldTemplates" property does not. If i use Coffescript native inheritance it will just throw and exception with "before" not defined (I can get the actual error if you want). If I define "projectHeaderNav: {to: 'header'}" in "Router.configure" it works fine. 

Any ideas?
