### ISSUE TITLE
CSS :target pseudo class

### ISSUE THREAD

**Issue by iBobik** [iron-meteor/iron-router#711]
Hi,
I have Meteor app with Iron Router and basically this code:

``` html
<a href="#new">New item</a>

<div id="new" class="dialog">
  <a href="#" class="dialog__close-btn"></a>
  <h2 class="dialog__title">New item</h2>
</div>
```

``` css
.dialog {
  display: none;
}

.dialog:target {
  display: block;
}
```

When I click the link, hash in url changes but dialog is still hidden. When I removed Iron Router from my project it works.

It seems there is some bug what destroys standard behavior in browser.
